/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/D4PFMr49MD6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function form() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Swap Tokens</CardTitle>
        <CardDescription>Enter the details to swap your tokens.</CardDescription>
      </CardHeader>
      <CardContent>
        <form className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="token0">Token 0</Label>
            <Input id="token0" placeholder="Enter token 0" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="token1">Token 1</Label>
            <Input id="token1" placeholder="Enter token 1" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="amount">Amount</Label>
            <Input id="amount" placeholder="Enter amount" type="number" />
          </div>
          <Button className="w-full" type="submit">
            Swap
          </Button>
        </form>
      </CardContent>
    </Card>
  )
}
